name: Build with RMPP Toolchain

on:
    push:
        branches:
          - master

jobs:
    build:
        runs-on: ubuntu-latest

        container:
            image: eeems/remarkable-toolchain:latest-rmpp

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Install CMake
              run: |
                apt-get update
                apt-get install -y cmake

            - name: Build Application
              shell: bash
              run: |
                source /opt/codex/ferrari/*/environment-setup-cortexa53-crypto-remarkable-linux
                mkdir build
                cd build
                cmake ..
                make -j$(nproc)

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: xovi.so
                path: build/xovi.so


