name: Build with RMPP Toolchain

on:
    push:
        branches:
          - master

jobs:
    build:
        runs-on: ubuntu-latest

        container:
            image: eeems/remarkable-toolchain:latest-rmpp

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Build Application
              run: |
                mkdir ~/Tools
                ln -rs /opt/codex/ferrari/* ~/Tools/remarkable-toolchain
                bash make_shared_rmpp_aarch64

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: xovi.so
                path: xovi.so


